---

- name: Make artifacts directory
  file:
    path: "{{ artifacts_dir }}"
    state: directory

- name: Download Raspberry Pi OS
  get_url:
    url: "{{ download_links[mirror][image] }}"
    dest: "{{ artifacts_dir }}/{{ download_links[mirror][image] | basename }}"
    use_proxy: no