---

- name: Make artifacts directory
  file:
    path: "{{ playbook_dir }}/artifacts"
    state: directory

- name: Download Raspberry Pi OS
  get_url:
    url: "{{ download_links[mirror][image] }}"
    dest: "{{ playbook_dir}}/artifacts/{{ download_links[mirror][image] | basename }}"
    use_proxy: no