---
# configure role

- hosts: netboot
  gather_facts: false # the inventory probably contains non-existent hosts
  connection: local
  tasks:
    - name: Start configure role
      include_role:
        name: configure
      vars:
        host: "{{ (loop_var.keys() | list) | first }}"
        ip: "{{ (loop_var.values() | list)[0].ip | replace(':','-') | lower }}"
        nfs_host: "{{ hostvars['localhost']['nfs']['host'] }}"
        nfs_tftp_dir: "{{ hostvars['localhost']['nfs']['tftp_dir'] }}"
        nfs_filesystem_dir: "{{ hostvars['localhost']['nfs']['filesystems_dir'] }}/{{ (loop_var.keys() | list) | first }}"
        filesystem_dir: "{{ hostvars['localhost']['filesystems_dir'] }}/{{ (loop_var.keys() | list) | first }}"
      loop: "{{ hostvars['localhost']['hosts'] }}"
      loop_control:
        loop_var: loop_var
