---
# download role

- hosts: netboot
  gather_facts: no    # the inventory probably contains non-existent hosts
  connection: local
  tasks:
    - name: Start download role
      include_role:
        name: download
      vars:
        image: "{{ (loop_var.values() | list)[0].image }}"
      loop: "{{ hostvars['localhost']['hosts'] }}"
      loop_control:
        loop_var: loop_var