---
- name: "Start a TFTP docker container"
  docker_container:
    name: "{{ hostvars['localhost']['tftp_container']['name'] }}"
    image: "{{ hostvars['localhost']['tftp_container']['image'] }}"
    state: started
    restart_policy: unless-stopped
    detach: true
    pull: true
    volumes:
      - "{{ hostvars['localhost']['tftp_dir'] }}:/tftproot:shared"
      - /etc/localtime:/etc/localtime:ro
    command: -directory /tftproot -timeout 60
    network_mode: host
