---
- name: "Start a TFTP docker container"
  docker_container:
    name: "{{ hostvars['localhost']['tftp_container']['name'] }}"
    image: "{{ hostvars['localhost']['tftp_container']['image'] }}"
    state: started
    restart_policy: unless-stopped
    detach: true
    ports:
      - "69:69/udp"
    volumes:
      - "{{ hostvars['localhost']['tftp_dir'] }}:/tftproot"
      - /etc/localtime:/etc/localtime:ro
    command: -directory /tftproot
