---
- name: "Configure /etc/hosts"
  template:
    src: "hosts.j2"
    dest: "{{ filesystem_dir }}/etc/hosts"
    owner: root
    group: root
    mode: 0644
  become: true

- name: "Configure /etc/hostname"
  template:
    src: "hostname.j2"
    dest: "{{ filesystem_dir }}/etc/hostname"
    owner: root
    group: root
    mode: 0644
  become: true

- name: "Configure /etc/fstab"
  template:
    src: "fstab.j2"
    dest: "{{ filesystem_dir }}/etc/fstab"
    owner: root
    group: root
    mode: 0644
  become: true

- name: "Configure /boot/cmdline.txt"
  template:
    src: "cmdline.j2"
    dest: "{{ nfs_tftp_dir }}/{{ ip }}/cmdline.txt"
    owner: root
    group: root
    mode: 0644
  become: true

- name: "Enable SSH (part 1)"
  file:
    src: /lib/systemd/system/ssh.service
    dest: "{{ filesystem_dir }}/etc/systemd/system/sshd.service"
    owner: root
    group: root
    state: link
  become: true

- name: "Enable SSH (part 2)"
  file:
    src: /lib/systemd/system/ssh.service
    dest: "{{ filesystem_dir }}/etc/systemd/system/multi-user.target.wants/ssh.service"
    owner: root
    group: root
    state: link
  become: true

- name: "Read current user's public SSH key"
  slurp:
    src: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  register: ssh_key

- name: "Copy SSH key"
  lineinfile:
    create: yes
    line: "{{ ssh_key['content'] | b64decode }}"
    path: "{{ filesystem_dir }}/home/pi/.ssh/authorized_keys"
