# This is a basic workflow to help you get started with Actions

name: Ansible

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Put ssh public key in authorized_keys
      - name: "Add SSH key"
        run: |
          ssh-keygen -t rsa -b 4096 -C "{{ github.actor }}@{{ github.host }}" -f ~/.ssh/id_rsa -N ""
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

      # Runs a single command using the runners shell
      - name: Run download.yml
        run: ansible-playbook -i inventory.yml download.yml

      - name: Run install.yml
        run: ansible-playbook -i inventory.yml install.yml
