name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-docker

      - name: Run download.yml
        run: ansible-playbook -i inventory.yml download.yml --extra-vars 'mirror=jrcichra.dev'

      - name: Run build.yml
        run: ansible-playbook -i inventory.yml build.yml --extra-vars 'mirror=jrcichra.dev'

      - name: Run tftp.yml
        run: ansible-playbook -i inventory.yml tftp.yml --extra-vars 'mirror=jrcichra.dev'
